#ifndef BRISONUS_PRODUCT_BUNDLE_FIRMWARE_BUNDLE_FIRMSOFTRESET_H_
#define BRISONUS_PRODUCT_BUNDLE_FIRMWARE_BUNDLE_FIRMSOFTRESET_H_

#include <services/rcu/adi_rcu.h>



uint32_t ulFSoftRest(void);


#endif /* BRISONUS_PRODUCT_BUNDLE_FIRMWARE_BUNDLE_FIRMSOFTRESET_H_ */
